/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Napakalaki.Monster;

/**
 *
 * @author jesusjimsa
 */
public class MonsterView extends javax.swing.JPanel {

	private Monster monsterModel;

	/**
	 * Creates new form MonsterView
	 */
	public MonsterView() {
		initComponents();
		repaint();
	}

	public void setMonster(Monster m) {
		monsterModel = m;
		monsterName.setText(monsterModel.getName());
		monsterLevel.setText(Integer.toString(monsterModel.getCombatLevel()));
		monsterLevel.setText(Integer.toString(monsterModel.getCombatLevel()));
		prizeView.setPrize(monsterModel.getPrize());
		bcView.setBadConsequence(monsterModel.getBadConsequence());
		hideMonster();
		repaint();
	}

	public void showMonster() {
		// Mostramos los paneles del monstruo
		prizeView.setVisible(true);
		actualMonster.setVisible(true);
		bcView.setVisible(true);
		combatLevelDisplay.setVisible(true);
		imgMonstruo.setVisible(true);
		imgMonstruo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Monstruos/" + Integer.toString(monsterModel.getIcon()) + ".png")));
		repaint();
	}

	public void hideMonster() {
		// Ocultamos los paneles correspondientes
		prizeView.setVisible(false);
		actualMonster.setVisible(false);
		combatLevelDisplay.setVisible(false);
		bcView.setVisible(false);
		imgMonstruo.setVisible(false);
		repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prizeView1 = new GUI.PrizeView();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        prizeView = new GUI.PrizeView();
        combatLevelDisplay = new javax.swing.JPanel();
        monsterLevel = new javax.swing.JLabel();
        imgMonstruo = new javax.swing.JLabel();
        actualMonster = new javax.swing.JPanel();
        monsterName = new javax.swing.JLabel();
        bcView = new GUI.PendingBadConsequenceView();

        jScrollPane1.setViewportView(jEditorPane1);

        jFormattedTextField1.setText("jFormattedTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(204, 255, 204));

        prizeView.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        combatLevelDisplay.setBackground(new java.awt.Color(204, 255, 204));
        combatLevelDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nivel de combate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 8))); // NOI18N

        monsterLevel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monsterLevel.setText("Nivel");

        javax.swing.GroupLayout combatLevelDisplayLayout = new javax.swing.GroupLayout(combatLevelDisplay);
        combatLevelDisplay.setLayout(combatLevelDisplayLayout);
        combatLevelDisplayLayout.setHorizontalGroup(
            combatLevelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combatLevelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monsterLevel)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        combatLevelDisplayLayout.setVerticalGroup(
            combatLevelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combatLevelDisplayLayout.createSequentialGroup()
                .addComponent(monsterLevel)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        imgMonstruo.setBackground(new java.awt.Color(204, 255, 204));
        imgMonstruo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgMonstruo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Monstruos/1.png"))); // NOI18N

        actualMonster.setBackground(new java.awt.Color(169, 255, 169));
        actualMonster.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Monstruo actual"));

        monsterName.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        monsterName.setText("Monstruo");

        javax.swing.GroupLayout actualMonsterLayout = new javax.swing.GroupLayout(actualMonster);
        actualMonster.setLayout(actualMonsterLayout);
        actualMonsterLayout.setHorizontalGroup(
            actualMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualMonsterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monsterName, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        actualMonsterLayout.setVerticalGroup(
            actualMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monsterName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(actualMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(imgMonstruo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(combatLevelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prizeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bcView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combatLevelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(imgMonstruo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bcView, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actualMonster;
    private GUI.PendingBadConsequenceView bcView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel combatLevelDisplay;
    private javax.swing.JLabel imgMonstruo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel monsterLevel;
    private javax.swing.JLabel monsterName;
    private GUI.PrizeView prizeView;
    private GUI.PrizeView prizeView1;
    // End of variables declaration//GEN-END:variables
}
