/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Napakalaki.*;

/**
 *
 * @author jesusjimsa
 */
public class NapakalakiView extends javax.swing.JFrame {
	
	Napakalaki napakalakiModel = new Napakalaki();
	
	public void setNapakalaki(Napakalaki napakalaki){
            
		napakalakiModel = napakalaki;
                
                this.playerView.setNapakalaki(napakalaki, this);
                this.playerView.setPlayer(napakalaki.getCurrentPlayer());
                this.monsterView.setMonster(napakalaki.getCurrentMonster());
                
                repaint();
	}
	
	/**
	 * Creates new form NapakalakiView
	 */
	public NapakalakiView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerView = new GUI.PlayerView();
        monsterView = new GUI.MonsterView();
        meetMonsterButton = new javax.swing.JButton();
        nextTurnButton = new javax.swing.JButton();
        combatButton = new javax.swing.JButton();
        resultadoCombate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerView.setBorder(new javax.swing.border.MatteBorder(null));

        monsterView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        meetMonsterButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        meetMonsterButton.setText("Meet the Monster");
        meetMonsterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterButtonActionPerformed(evt);
            }
        });

        nextTurnButton.setBackground(new java.awt.Color(255, 153, 0));
        nextTurnButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nextTurnButton.setText("Next turn");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });

        combatButton.setBackground(new java.awt.Color(204, 0, 0));
        combatButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        combatButton.setText("Combat");
        combatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatButtonActionPerformed(evt);
            }
        });

        resultadoCombate.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(monsterView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(meetMonsterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(combatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextTurnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(resultadoCombate)
                        .addGap(287, 287, 287))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monsterView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nextTurnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meetMonsterButton)
                            .addComponent(combatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(resultadoCombate))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public void checkPendingBadConsequence(){
		if(!combatButton.isEnabled() && napakalakiModel.nextTurnAllowed()){
			nextTurnButton.setEnabled(true);
		}
	}
	
	public void showView() {
		this.setVisible(true);
	}
	
    private void meetMonsterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterButtonActionPerformed
		monsterView.showMonster();
		combatButton.setEnabled(true);
		meetMonsterButton.setEnabled(false);
		playerView.ChangeMakeVisibleButton(false);
    }//GEN-LAST:event_meetMonsterButtonActionPerformed

    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnButtonActionPerformed
        if(napakalakiModel.nextTurn()){
			playerView.setPlayer(napakalakiModel.getCurrentPlayer());
			monsterView.setMonster(napakalakiModel.getCurrentMonster());
			meetMonsterButton.setEnabled(true);
			nextTurnButton.setEnabled(false);
		}
    }//GEN-LAST:event_nextTurnButtonActionPerformed

    private void combatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatButtonActionPerformed
		CombatResult combatResult = napakalakiModel.developCombat();

		if (combatResult == CombatResult.WIN)
			resultadoCombate.setText("Has ganado el combate :D");
		else
			if (combatResult == CombatResult.LOSE)
			resultadoCombate.setText("Has perdido el combate T.T");
		else
			if (combatResult == CombatResult.LOSEANDCONVERT)
			resultadoCombate.setText("Pierdes el combate y te conviertes en sectario :(");
		else
			if (combatResult == CombatResult.WINGAME) {
			resultadoCombate.setText("Has ganado el juego.\nBIEEEEEN!!");
    }//GEN-LAST:event_combatButtonActionPerformed

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combatButton;
    private javax.swing.JButton meetMonsterButton;
    private GUI.MonsterView monsterView;
    private javax.swing.JButton nextTurnButton;
    private GUI.PlayerView playerView;
    private javax.swing.JLabel resultadoCombate;
    // End of variables declaration//GEN-END:variables
}
