/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author jesusjimsa
 */
public class PlayerNamesCapture extends javax.swing.JDialog {
	ArrayList<String> names = new ArrayList();

	/**
	 * Creates new form PlayerNamesCapture
	 * @param parent
	 * @param modal
	 */
	public PlayerNamesCapture(JFrame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.addWindowListener (new WindowAdapter() {
		
			@Override
			public void windowClosing (WindowEvent e) {
				System.exit(0);
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
	 * The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoJugadores = new javax.swing.JLabel();
        textoj2 = new javax.swing.JLabel();
        textoj3 = new javax.swing.JLabel();
        textoj1 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        name3 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        Play = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Kitty = new javax.swing.JLabel();
        winnie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 204));
        setForeground(java.awt.Color.pink);

        textoJugadores.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        textoJugadores.setForeground(new java.awt.Color(255, 0, 255));
        textoJugadores.setText("Jugadores");

        textoj2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        textoj2.setText("Jugador 2 :D");

        textoj3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        textoj3.setText("Jugador 3 XD");

        textoj1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        textoj1.setText("Jugador 1 :)");

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });

        name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name3ActionPerformed(evt);
            }
        });

        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });

        Play.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Play.setText("Play ;D");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        Cancel.setBackground(new java.awt.Color(255, 0, 51));
        Cancel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Cancel.setText("Cancel :(");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Kitty.setIcon(new javax.swing.ImageIcon("/Users/jesusjimsa/Dropbox (Personal)/Documentos/Universidad/2 - Primer cuatrimestre/Programación y Diseño Orientado a Objetos/Prácticas/napakalaki/src/GUI/kitty_2.png")); // NOI18N

        winnie.setIcon(new javax.swing.ImageIcon("/Users/jesusjimsa/Dropbox (Personal)/Documentos/Universidad/2 - Primer cuatrimestre/Programación y Diseño Orientado a Objetos/Prácticas/napakalaki/src/GUI/7843.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoj1)
                            .addComponent(textoj2)
                            .addComponent(textoj3))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(winnie)
                        .addGap(65, 65, 65)
                        .addComponent(textoJugadores)
                        .addGap(35, 35, 35)
                        .addComponent(Kitty)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winnie)
                            .addComponent(Kitty)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(textoJugadores)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoj1)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoj2)
                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoj3)
                    .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        //Añadir los nombres de los jugadores
		if (!name1.getText().isEmpty())
			names.add (name1.getText());
		
		if (!name2.getText().isEmpty())
			names.add (name2.getText());
		
		if (!name3.getText().isEmpty())
			names.add (name3.getText());
		
		//Cerrar la ventana
		this.dispose();
    }//GEN-LAST:event_PlayActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name3ActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public ArrayList<String> getNames(){
		this.setVisible(true);
		
		return names;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Kitty;
    private javax.swing.JButton Play;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JLabel textoJugadores;
    private javax.swing.JLabel textoj1;
    private javax.swing.JLabel textoj2;
    private javax.swing.JLabel textoj3;
    private javax.swing.JLabel winnie;
    // End of variables declaration//GEN-END:variables
}
