/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Napakalaki.*;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author jesusjimsa
 */
public class PlayerView extends javax.swing.JPanel {

	private Player playerModel;
	private Napakalaki napakalakiModel;
	private NapakalakiView napakalakiView;
	
	/**
	 * Creates new form PlayerView
	 */
	public PlayerView() {
		initComponents();
	}
	
	public void setNapakalaki(Napakalaki model, NapakalakiView view){
		napakalakiModel = model;
		napakalakiView = view;
	}
        
	
	
	
	public void setPlayer(Player model) {
		playerModel = model;
		
		String name = playerModel.getName();
		String level = Integer.toString(playerModel.getLevels());
		
		playerName.setText(name);
		levelNumber.setText(level);
		
		fillTreasurePanel(visibleTreasures, playerModel.getVisibleTreasures());
		fillTreasurePanel(hiddenTreasures, playerModel.getHiddenTreasures());
		
		// cultistView.setCultist(model);
		
		repaint();
		
		revalidate();
	}
	
	private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
		// Se elimina la información antigua
		aPanel.removeAll();
		
		// Se recorre la lista de tesoros construyendo y añadiendo sus vistas al panel
		for (Treasure t : aList ) {
			TreasureView aTreasureView = new TreasureView();
			aTreasureView.setTreasure(t);
			aTreasureView.setVisible(true);
			
			aPanel.add(aTreasureView);
		}
		
		// Se fuerza la actualización visual del panel
		aPanel.repaint();
		aPanel.revalidate();
	}
        
        public ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
            // Se recorren los tesoros que contiene el panel,
            //    almacenando en un vector aquellos que están seleccionados.
            //    Finalmente se devuelve dicho vector.
            TreasureView tv;
            ArrayList<Treasure> output = new ArrayList();
            for (Component c : aPanel.getComponents()) {


                tv = (TreasureView) c;
                if (tv.isSelected()) {
                    output.add(tv.getTreasure());
                }
            }
            return output;
        }	

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        playerName = new javax.swing.JLabel();
        levelNumber = new javax.swing.JLabel();
        descartarT = new javax.swing.JButton();
        hacerVisibleButton = new javax.swing.JButton();
        hiddenTreasures = new javax.swing.JPanel();
        visibleTreasures = new javax.swing.JPanel();
        cultistView2 = new GUI.CultistView();
        robarButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        playerName.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        playerName.setText("Nombre");

        levelNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        levelNumber.setText("Nivel");

        descartarT.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        descartarT.setText("Descartar tesoro");
        descartarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarTActionPerformed(evt);
            }
        });

        hacerVisibleButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        hacerVisibleButton.setText("Hacer visible");
        hacerVisibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerVisibleButtonActionPerformed(evt);
            }
        });

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout hiddenTreasuresLayout = new javax.swing.GroupLayout(hiddenTreasures);
        hiddenTreasures.setLayout(hiddenTreasuresLayout);
        hiddenTreasuresLayout.setHorizontalGroup(
            hiddenTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hiddenTreasuresLayout.setVerticalGroup(
            hiddenTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        visibleTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout visibleTreasuresLayout = new javax.swing.GroupLayout(visibleTreasures);
        visibleTreasures.setLayout(visibleTreasuresLayout);
        visibleTreasuresLayout.setHorizontalGroup(
            visibleTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        visibleTreasuresLayout.setVerticalGroup(
            visibleTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        robarButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        robarButton.setText("Robar tesoro");
        robarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerName)
                            .addComponent(levelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descartarT))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hacerVisibleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(cultistView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(robarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(playerName)
                .addGap(18, 18, 18)
                .addComponent(levelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cultistView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descartarT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hacerVisibleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(robarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descartarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarTActionPerformed
        ArrayList<Treasure> visibles = getSelectedTreasures(visibleTreasures);
		napakalakiModel.discardVisibleTreasures(visibles);
		
		ArrayList<Treasure> escondidos = getSelectedTreasures(hiddenTreasures);
		napakalakiModel.discardHiddenTreasures(escondidos);
		
		setPlayer(napakalakiModel.getCurrentPlayer());
		
		repaint();
    }//GEN-LAST:event_descartarTActionPerformed

    private void hacerVisibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerVisibleButtonActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
		
        napakalakiModel.makeTreasuresVisible(selHidden);
        
		setPlayer(napakalakiModel.getCurrentPlayer());
		
		repaint();
		
        napakalakiView.checkPendingBadConsequence();
    }//GEN-LAST:event_hacerVisibleButtonActionPerformed

    private void robarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robarButtonActionPerformed
        Treasure robado = playerModel.stealTreasure();

		setPlayer(napakalakiModel.getCurrentPlayer());
		robarButton.setEnabled(false);
		hacerVisibleButton.setEnabled(true);
    }//GEN-LAST:event_robarButtonActionPerformed

	ArrayList<Treasure> selectedTreasures(JPanel panel){
		ArrayList<Treasure> elegidos = new ArrayList();
		TreasureView tv;
		
		for (Component c : panel.getComponents()) {
			tv = (TreasureView) c;

			if (tv.isSelected()) {
				elegidos.add(tv.getTreasure());
			}
		}

		return elegidos;
	}
	
	public void ChangeMakeVisibleButton (boolean value){
		if (value){
			if (playerModel.getHiddenTreasures().size() > 0)
				hacerVisibleButton.setEnabled(true);
		}
		else
			hacerVisibleButton.setEnabled(false);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CultistView cultistView2;
    private javax.swing.JButton descartarT;
    private javax.swing.JButton hacerVisibleButton;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelNumber;
    private javax.swing.JLabel playerName;
    private javax.swing.JButton robarButton;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
