/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Napakalaki.*;

/**
 *
 * @author jesusjimsa
 */
public class PrizeView extends javax.swing.JPanel {
	private Prize prizeModel;

	/**
	 * Creates new form PrizeView
	 */
	public PrizeView() {
		initComponents();
	}
	
	public void setPrize(Prize prize){
		prizeModel = prize;
		
		premio.setText(prizeModel.toString());
		
		repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        premio = new javax.swing.JLabel();

        titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        titulo.setText("Premio");

        premio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        premio.setText("Esperando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(premio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(premio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel premio;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
