/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Napakalaki.Treasure;
import Napakalaki.TreasureKind;

/**
 *
 * @author jesusjimsa
 */
public class TreasureView extends javax.swing.JPanel {
	
	Treasure treasureModel;
        boolean selected = false;

	/**
	 * Creates new form TreasureView
	 */
	public TreasureView() {
		initComponents();
                repaint();
	}
	
	public void setTreasure(Treasure t) {
		
		treasureModel = t;
		treasureName.setText(treasureModel.getName());
		bonusNumber.setText(Integer.toString(treasureModel.getBonus()));
		
                TreasureKind type = treasureModel.getType();
                switch (type) {
                    case ARMOR:
                        treasureKindName.setText("ARMOR");
                        break;
                    case ONEHAND:
                        treasureKindName.setText("ONE HAND");
                        break;
                    case BOTHHANDS:
                        treasureKindName.setText("BOTH HANDS");
                        break;
                    case SHOES:
                        treasureKindName.setText("SHOES");
                        break;
                    case HELMET:
                        treasureKindName.setText("HELMET");
                        break;
                }
		
		// treasureImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(treasureModel.getIcon)));
                formMouseClicked(null);
                repaint();
	}
        
        public boolean isSelected() {
            return selected;
        }
        
        public Treasure getTreasure() {
            return treasureModel;
        }
        
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bonusNumber = new javax.swing.JLabel();
        treasureName = new javax.swing.JLabel();
        treasureKindName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        bonusNumber.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bonusNumber.setForeground(new java.awt.Color(255, 255, 102));
        bonusNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonusNumber.setText("Bonus");

        treasureName.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        treasureName.setText("Nombre Tesoro");

        treasureKindName.setFont(new java.awt.Font("Comic Sans MS", 2, 10)); // NOI18N
        treasureKindName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        treasureKindName.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(treasureName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(treasureKindName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bonusNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(treasureName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treasureKindName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bonusNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (selected == true) {
            selected = false;
            setBackground(new java.awt.Color(204,204,204));
            repaint();
        }
        else {
            selected = true;
            setBackground(new java.awt.Color(153,204,255));
            repaint();
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonusNumber;
    private javax.swing.JLabel treasureKindName;
    private javax.swing.JLabel treasureName;
    // End of variables declaration//GEN-END:variables
}
